### ISSUE TITLE
The MAP decoding results 

### ISSUE THREAD

**Issue by ledihdug** [levylv/deep-neural-network-decoder#1]
In figure 8, 9, and 10 of your paper, you compared the BER of NNDs with MAP decoding. Could you show me how to calculate the results for the MAP decoding? I tried to find in this repository and haven't found yet? 
Thanks you so much

**Comment by levylv** [comment]
Thanks for your patient reading. Yes, we don't upload our MAP decoding code in this repository, because it is irrelevant with our core content. Specifically, we use SCL as MAP decoding algorithm, it is the typical decoding algorithm of polar code which could reach the MAP performance.

-

**Comment by levylv** [comment]
Thanks for your patient reading. Yes, we don't upload our MAP decoding code in this repository, because it is irrelevant with our core content. Specifically, we use SCL as MAP decoding algorithm, it is the typical decoding algorithm of polar code which could reach the MAP performance.

-

在 2018年4月10日，下午3:27，ledihdug <notifications@github.com<mailto:notifications@github.com>> 写道：


In figure 8, 9, and 10 of your paper, you compared the BER of NND with MAP decoding. Could you show me how to calculate the results for the MAP decoding? I tried to find in this repository and haven't found yet?
Thanks you so much

—

**Comment by ledihdug** [comment]
I also tried SC as MAP decoding but the results were a little bit worse than yours.  
Thank you very much for the prompt reply. 
Best regards,
